### ISSUE TITLE
Bug-ish : r140 : Items that can not be random assigned to raid

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#100]
Oxian Hide Boots : Medium ilvl 55 : Stalker only
but seems to be carbine problem, since without masterloot injection there is no difference

**Comment by Drutol** [comment]
It displays only stalkers?

**Comment by Hysteriana** [comment]
yes

with injection
![1](https://cloud.githubusercontent.com/assets/11199863/6836079/662234c2-d33f-11e4-87c9-6e882628704e.png)

without injection
![2](https://cloud.githubusercontent.com/assets/11199863/6836084/6a273162-d33f-11e4-88ce-d9332fc4657f.png)

item tooltip ( i dont see anything that suggests stalker only )
![3](https://cloud.githubusercontent.com/assets/11199863/6836115/a2d790f6-d33f-11e4-86c2-09b81bdcea41.png)

**Comment by Drutol** [comment]
Hmm, since I'm not able to experience this , I'll send you a debug code snippet which will spam your chatlog with names. The way Master Loot works is that it provides a table with items , each item has own table with people eligible to get this item , so if this table contains only stalkers it's beyond my ability to do anything.

**Comment by Drutol** [comment]
As it turns out it's something on the carbine's side...
