### ISSUE TITLE
Other People Running Master Addon

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#149]
First, this isn't an issue so much as a question.

I'm looking to have my officers run the RaidOps addon (in addition to having them run the membermodule so they can bid). The reason is I want them all to be able to fetch from me just in case I crash, I'll be able to fetch from them rather than having to redo everything since my last reloadui. Whenever I have all three addons running, I get a debug message to the effect of making sure I have the right addons loaded. I assume this has something to do with there being a conflict with the member module and the main addon. Can you confirm/deny this? Also, if they all run the main RaidOps module, will they have issues bidding?

**Comment by Drutol** [comment]
So , master addon can do almost everything that member module and master loot addons can do. Having RaidOps instead of member module won't (or at least shouldn't) differ much from member module in terms of bidding.

Member module won't allow you to enable GP values on tooltip display if it finds master addon.

Master loot addon won't load at all if there's master addon or default master loot addon is not found. They would run into conflict other wise.
