### ISSUE TITLE
Bug: Error on DB import

### ISSUE THREAD

**Issue by coden1ke** [Mordonus/RaidOps#271]
`...WildStar\Addons\RaidOpsMemberModule\libs/Serpent.lua:133: attempt to call a nil value
stack trace:
    ...WildStar\Addons\RaidOpsMemberModule\libs/Serpent.lua:133: in function 'load'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4017: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3926>`

Some background: I needed to check on an older DB, I created a new DB backup and imported the DB I wanted to look at - everything was fine. When I attempted to import the latest DB backup I received that error posted above. 

If needed here is the DB I am trying to import: http://pastebin.com/raw.php?i=NhV5wwQ8

**Comment by Drutol** [comment]
Hmm the problem is in the string itself , it got corrupted somehow.

You can decode this string using this webiste : https://www.base64decode.org/
As you can see there are some oddities near the bottom of the file.

Or in the picture here:
![image](https://cloud.githubusercontent.com/assets/6102530/8485113/aa8da092-20fb-11e5-84b8-92807496ceb4.png)

It may be a rare bug in 3rd party library I'm using , I'll ditch this encoding and leave this as raw as possible with next update to avoid such things. For the time being you can use website export as it's importable too , it doesn't save settings though.

Sorry for inconvenience!

**Comment by coden1ke** [comment]
No problem at all, thanks a ton!
