### ISSUE TITLE
Networking status

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#345]
I'm just curious whether everything works as I haven't touched it in quite some time. So anyone is using it?

I mean things from windows:
- Data Sharing
- Data Sync
- Network Bidding (is it in use at all?)

**Comment by Hysteriana** [comment]
since using the webpage, i dont have much need for the sharing/sync, cause it was only for backup purpose in case of dc or client crash. maybe some are using the member module but i dont think so.
never used the network bidding.

**Comment by gmagnanti** [comment]
I am not able to sync/share data at all.  The wiki refers to needing a guild channel name set in the data sharing menu, but I don't even have a place to type that in on mine.  Not sure if that's been removed since that wiki was written, but my guild members are not able to fetch from me at all.  I have data sharing enabled and they are typing in my name, pressing enter and clicking fetch.  No dialog pops up at all.
