### ISSUE TITLE
Not able to import from website or sync with other person

### ISSUE THREAD

**Issue by mpangelu** [Mordonus/RaidOps#376]
No idea if there are some steps I need to go through. I've also purged previous database, but I'm currently trying to take the downloaded file, open it, select all, copy, go to import/export. Select importable database, select epgp and then select import/export. Reloadui happens, I open back up epgp and nothing is different.

When going to data sync I've tried several times to fetch data and nothing happens.

I've tried deleting the addon and unzipping a fresh install and then taking the information to try again but same results.

**Comment by Drutol** [comment]
I'm currently redesigning export window so there should be less confusion.

There are 2 types of importable database (By the addon):
- Website export
  - Contains only info that is used by website i.e. player information.
- Importable database
  - Contains all info with addon settings , players etc.

You can import them but due to UI limitations you have to split this text into 30k character chunks , paste one into text box , press "+" button , paste next and repeat until you pasted whole thing. Now you have to select "Import database" and press "Import/Export" button. You can also go to addon installation folder and there is file named IMPORT_STRING_HERE.lua , there are instructions inside.(Don't leave space in the beginning of the string)

The rest of export types are just extracted data into CSV or HTML for you to use.

**Comment by Drutol** [comment]
As far as sync is concerned: 
- Was the player you wanted to fetch from in your guild and online?
- Did this player had sync enabled?
  *,Did this player get any sync logs?

Carbine has made syncing very hard with drop 5 , and while it was working during my testing , I don't have any signals that somebody uses it.

**Comment by mpangelu** [comment]
Yeah he was online and in guild and in my raid, he had sync enabled.
Apparently he removed the history or something and it was able to import
well, but the data that I was trying to import had the activity
logs/history I think and it wasn't able to be imported.

**Comment by Drutol** [comment]
I don't attach activity log to any of importable exports. Next version of export window has indicator whether the data is correct or not so there will be less confusion.

I'll try to tinker with sync but I don't promise anything :(

(Try to check whether he gets those sync logs.)
