### ISSUE TITLE
Raid Summaries and Grand plan of things.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#64]
Having gone through most of the issues , it's time to get back to raid summaries. I have already some concepts/ideas , but I'd like to hear from you how would you like them to be. Are they even necessary? What they should track? Or maybe I should focus on something else (wiki , application to create backups etc.) ?  Point me in general direction of things you think would be useful.

**Comment by Aeotoc** [comment]
Let me come up with a list because in my opinion, the Raid Summaries needs to be the thing that I _want_ to export every raid night because of how comprehensive it is.

**Comment by Aeotoc** [comment]
- Raid Summary Dates should be toggle-able between DD/MM/YYYY to MM/DD/YY(YY). 
- Needs a changeable "Start Time" rather than just always starting whenever I click "New Session," If I could click "New Session" and set a time for it to start, it would help keep raid times accurate. I say this because I often start the summary before I pull by a good 10-15 minutes to get everything setup. 
- The attendance tracker needs an On-Time tracker as well, so that way I know exactly who was on time each night. 
- In addition to the logs given to me by the dkp module, I also want EPGP logs viewable in this module. However, rather than a typical log, I think it'd be cool if it showed Columns: Name, Boss Kills, Mini Boss Kills, and Time spent inside the Raid.

I'll think of more later.

**Comment by xeroiv** [comment]
Are EPGP logs supposed to be viewable in the member module?  I had a guildee try to see the point history from the member module but wasnt able to.  Not certain if he was up to the latest version of the member module though.  
But on to things that would be helpful:
- I would like to see a way to view a list of all the EPGP entries rather than on a player by player basis.
- I would also like to request a way to fix the minimum GP to not decay below a value of 1.

**Comment by Drutol** [comment]
- Hmm, how about filtering Modification Types in recent activity log? This is something that does what you want.
- I will add a barrier for GP so it won't go below this threshold.
- Make sure that you have enabled logs sharing in Data Sharing window , there should also be entry of him trying to fetch data. Also remember that member needs to input your name **exactly** as it is in standings window.

**Comment by Aeotoc** [comment]
Actually, I agree with Vit here. Even with the sorting filters or whatever, it's still not as comprehensive as I'd like for the raid wide logs, but I also think having something like that viewable on the raidsummary module would be a better fit because you'd have a larger window space to work with

**Comment by Drutol** [comment]
I don't think this was raid summaries related , at least this is how I perceived this.

**Comment by Aeotoc** [comment]
Any chance you could make it so that when i start the bid on an item for Network bidding it links the item in party chat so people can see the tooltip? i'm having random issues with members not being able to see the item tooltip

**Comment by xeroiv** [comment]
I just had a guildee check the ROPSMM to see if they could see their personal log or anyone elses once they fetched the data.  The View Logs button just produced an empty window was what I was informed.  The latest ROPSMM was used from what I was told.

I have log sharing enabled in the master module, I also tried with many other combinations of data sharing options turned on/off.

**Comment by Aeotoc** [comment]
Vit, get with me in game. My members are able to pull from me

**Comment by Drutol** [comment]
Just one thing , please open new issues instead of creating one big bin of stuff. It's easier for me to be on top of things and track what I have done and what I need to do next.
